### ISSUE TITLE
Link failure with `bundled_proj` feature

### ISSUE THREAD

**Issue by robinmoussu** [georust/proj#29]
I tried to build proj with the feature `bundled_proj` on my fedora 30 since Proj 7.0 aren't in the repo, but I got a link failure. Was my assumption that `bundled_proj` would download and build Proj 7.0 from source for me?

### Cargo.toml

```
[package]
name = "transform"
version = "0.1.0"
authors = ["Robin Moussu <moussu.robin@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proj = { version = "0.16", features = ["bundled_proj"] }
geo-types = "0.5"
assert_approx_eq = "1.1"
```

### src/main.rs

```
use proj::Proj;

use geo_types::Point;
use assert_approx_eq::assert_approx_eq;

fn main() {
    let from = "EPSG:2230";
    let to = "EPSG:26946";
    let ft_to_m = Proj::new_known_crs(&from, &to, None).unwrap();
    let result = ft_to_m
        .convert(Point::new(4760096.421921, 3744293.729449))
        .unwrap(); 
    assert_approx_eq!(result.x(), 1450880.29f64);
    assert_approx_eq!(result.y(), 1141263.01f64);
}
```

### `cargo build`

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.1asqkjk3k7ixl6zx.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.2681mjg2g6z9bivh.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.28zm14058s4yuwjn.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.2j17j5peblze6opf.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.2jgha6nmh4kj0dyv.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.2tncncqat6huxea7.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.2utm3xxp8ffopyrz.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.39vsdcc51utj53jh.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.3r74iirza2gxy0hj.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.3v7dnb83goqfhprl.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.3zueut1fhll7xfhp.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.41dbb5ves51j2w7n.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.4ef0by692cipe4xw.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.4zefe07pboib7n8f.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.5dm7jb90v8tyrml8.rcgu.o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.70oqx3mupdculkr.rcgu.o" "-o" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/transform-bdc862550f4f6879.4jtz2m3fpxr5xe14.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps" "-L" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/build/proj-sys-298128c67c6b993f/out/lib" "-L" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/libassert_approx_eq-e81f10bd1f83c9eb.rlib" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/libproj-dffd022518f913c9.rlib" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/libthiserror-8d27e2a343ff8828.rlib" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/libproj_sys-b09900959e6bd43e.rlib" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/liblibc-e8eba7335cdf1c32.rlib" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/libgeo_types-ba34af30d362b55c.rlib" "/home/rmoussu/dev/tour-generation/tour_generation/extract/transform/target/debug/deps/libnum_traits-7de0e66da3207489.rlib" "-Wl,--start-group" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-7c5e456310a1373c.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-b981d9b2a408308f.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-43d0ea1b5ae34d0d.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-09e7f22e773899cd.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-aa74f166651adf6e.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-22c386707b639611.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-db04c9c5cd3bcf45.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-bb27492f721492e8.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-6b95245dbf686e20.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-287409d75db2ecd3.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-a93f70ee2006b6e3.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-566cdfbcc94b4360.rlib" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-7bb8dddc7ce34e92.rlib" "-Wl,--end-group" "/home/rmoussu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b117658e17259aa6.rlib" "-Wl,-Bdynamic" "-lproj" "-lutil" "-ldl" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/bin/ld: cannot find -lproj
          collect2: error: ld returned 1 exit status
```

**Comment by urschrei** [comment]
The build script doesn't download `PRO`, the source is bundled in the `proj-sys` crate (https://github.com/georust/proj-sys/tree/master/PROJSRC).

Can you try explicitly specifying proj crate version 0.16.2, then running `cargo update` and then `cargo build`? I doubt it'll make a difference, but worth a try. Otherwise, you can try building `PROJ` from source, then specifying the `pkg_config` feature on the crate instead. Unfortunately, `bundled_proj` is difficult to test, given the heterogeneity of the Linux platform, and the capriciousness of linker behaviour…

**Comment by robinmoussu** [comment]
It changed something! But now it can't find `libproj.so.19`.

### Cargo.toml

```
proj = { version = "0.16.2", features = ["bundled_proj"] }
geo-types = "0.5"
assert_approx_eq = "1.1"
````

### cargo run

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/transform`
target/debug/transform: error while loading shared libraries: libproj.so.19: cannot open shared object file: No such file or directory
```

### ls **/*proj*.so* -l

```
lrwxrwxrwx. 1 rmoussu domain users       13 May 14 19:39 target/debug/build/proj-sys-d63ece34f7e325f8/out/build/lib/libproj.so -> libproj.so.19
lrwxrwxrwx. 1 rmoussu domain users       17 May 14 19:39 target/debug/build/proj-sys-d63ece34f7e325f8/out/build/lib/libproj.so.19 -> libproj.so.19.1.0
-rwxr-xr-x. 1 rmoussu domain users 36594520 May 14 19:39 target/debug/build/proj-sys-d63ece34f7e325f8/out/build/lib/libproj.so.19.1.0
lrwxrwxrwx. 1 rmoussu domain users       13 May 14 19:40 target/debug/build/proj-sys-d63ece34f7e325f8/out/lib64/libproj.so -> libproj.so.19
lrwxrwxrwx. 1 rmoussu domain users       17 May 14 19:40 target/debug/build/proj-sys-d63ece34f7e325f8/out/lib64/libproj.so.19 -> libproj.so.19.1.0
-rwxr-xr-x. 1 rmoussu domain users 36594520 May 14 19:39 target/debug/build/proj-sys-d63ece34f7e325f8/out/lib64/libproj.so.19.1.0
```

Note: I don't think it should change anything, but I built PROJ from source and install it systemwide with `git clone git@github.com:OSGeo/PROJ.git && cd PROJ && mkdir build && cd build && cmake .. && make && make test && sudo make install`.

**Comment by urschrei** [comment]
Hmm so `build.rs` definitely _built_ libproj, and the link step completed. What is going on…

**Comment by robinmoussu** [comment]
### `LD_LIBRARY_PATH="$PWD/target/debug/build/proj-sys-d63ece34f7e325f8`

```
/out/build/lib/:$LD_LIBRARY_PATH" cargo run
   Compiling transform v0.1.0 (/home/rmoussu/dev/tour-generation/tour_generation/extract/transform)
    Finished dev [unoptimized + debuginfo] target(s) in 0.42s
     Running `target/debug/transform`
```

So it's probably cargo not doing its job. I'm not familiar with this. Do you (as the crate author) have to specify where the `.so` are generated, or is it cargo alone? If it's cargo's responsibility, you can close this issue, and I will ask for help on cargo's side.

**Comment by urschrei** [comment]
Yes, you have to specify it in the `build.rs` script, and this information is passed to cargo, so I think the problem is at my end, unfortunately. Have you tried using `proj = { version = "0.16.2", features = ["bundled_proj"] }` for now?

**Comment by robinmoussu** [comment]
Yes, [see above](https://github.com/georust/proj/issues/29#issuecomment-628789623).

**Comment by urschrei** [comment]
Ah, sorry, typo: `proj = { version = "0.16.2", features = ["pkg_config"] }`

**Comment by robinmoussu** [comment]
No. I tried, but without success (`pkg_config` doesn't find the PROJ files that I compiled manually). I didn't looked more than 10s why, so it's probably my fault. I prefer much more the `bundled_proj` approach, given that I will have to repeat the build on multiple machines with different distribution.

**Comment by urschrei** [comment]
No prob. I'll try to figure out why it's not working as it should…

**Comment by robinmoussu** [comment]
Btw, no need to rush if you were doing anything else. Having to specify manually the LD_LIBRARY_PATH isn't blocking for me.

I also opened a question on the [user forum](https://users.rust-lang.org/t/ld-library-path-not-properly-set-for-cargo-run/42631).

**Comment by urschrei** [comment]
Another thing we can try, to get some more data:

add the following lines to your `Cargo.toml`:

    [lib]
    crate-type=["cdylib"]

Then rename your `main.rs` to `lib.rs`, run `cargo clean`, then `cargo build`.

That should generate a `libtransform.so` in `target/debug`

If you run `ldd target/debug/libtransform.so`, it should list its shared library paths…

**Comment by robinmoussu** [comment]
```
$ ldd target/debug/libtransform.so
	linux-vdso.so.1 (0x00007ffd639b6000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fb07aae2000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb07aac1000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb07aaa7000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb07a8e1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb07ab14000)
```

**Comment by urschrei** [comment]
Hmm that looks like it isn't linking libproj at all. Try this in `lib.rs`: https://gist.github.com/urschrei/2125ed63d00d4a2a2796acff3e8db205 and then build again?

**Comment by robinmoussu** [comment]
I modified `pub main()` to be `pub fn main()`.

```
	linux-vdso.so.1 (0x00007ffc7cd35000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f9c2d689000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9c2d668000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9c2d64e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9c2d488000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9c2d6bb000)
```

**Comment by urschrei** [comment]
@robinmoussu v0.20.0 has just been published – `bundled_proj` now statically links `libproj` and has removed some of its dependencies (as well as enabling network grid downloads and some other functionality). Could you try it and let me know if this improves matters?

**Comment by robinmoussu** [comment]
I did a `cargo clean` then rebuilt.
```
     Running `rustc --crate-name proj --edition=2018 /home/rmoussu/.cargo/registry/src/github.com-1ecc6299db9ec823/proj-0.20.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -Cembed-bitcode=no -C debuginfo=2 -C debug-assertions=on --cfg 'feature="bundled_proj"' -C metadata=60918e48eebb8530 -C extra-filename=-60918e48eebb8530 --out-dir /home/rmoussu/dev/tour-generation/tour_generation/target/debug/deps -L dependency=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/deps --extern geo_types=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/deps/libgeo_types-cf6d55ffd38f565f.rmeta --extern libc=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/deps/liblibc-5bbd43aee220c6a2.rmeta --extern num_traits=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/deps/libnum_traits-19de07676aac1611.rmeta --extern proj_sys=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/deps/libproj_sys-d53e85f4046fa520.rmeta --extern reqwest=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/deps/libreqwest-830ebd3ac62d7b8e.rmeta --extern thiserror=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/deps/libthiserror-ec46396edf50d254.rmeta --cap-lints allow -L native=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/build/proj-sys-264e59f46ea5662c/out/lib -L native=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/build/ring-1a00e7c3f2c0157a/out`
error: could not find native static library `proj`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `proj-sys`.

Caused by:
  process didn't exit successfully: `rustc --crate-name proj_sys --edition=2018 /home/rmoussu/.cargo/registry/src/github.com-1ecc6299db9ec823/proj-sys-0.18.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -Cembed-bitcode=no -C debuginfo=2 -C debug-assertions=on --cfg 'feature="bundled_proj"' -C metadata=d53e85f4046fa520 -C extra-filename=-d53e85f4046fa520 --out-dir /home/rmoussu/dev/tour-generation/tour_generation/target/debug/deps -L dependency=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/deps --cap-lints allow -L native=/home/rmoussu/dev/tour-generation/tour_generation/target/debug/build/proj-sys-264e59f46ea5662c/out/lib -l static=proj -l dylib=sqlite3 -l dylib=tiff -l dylib=stdc++` (exit code: 1)
```

I'm using a workspace. 3 of my crates have a dependency on proj. They all uses

```
proj = { version = "0.20.1", features = ["bundled_proj"] }
```

- OS - fedora 30
- rustc 1.45.1 (stable)

**Comment by urschrei** [comment]
Hmm. I wonder whether I've been too conservative in my link-search paths:

Your `libproj` built in `out/lib64` and `out/build/lib`, but `-L` is only looking in `/out/lib`.

`proj` 0.20.2 is on crates.io now, and includes these search paths…

**Comment by robinmoussu** [comment]
It's working, yeah! :rocket: :tada:

**Comment by simonhaines** [comment]
Just as another data point to this, I also use Fedora with its outdated Proj library. I was able to get a `bundled_proj` compiled by picking [a commit](https://github.com/georust/proj/commit/aae5680e1d98c84fcc0f7b7329bef9198d69a20d) that occurred after some changes to `bundled_proj` handling with the following dependency added to Cargo.toml:
```
proj = { git = "https://github.com/georust/proj", rev = "aae5680e1d98c84fcc0f7b7329bef9198d69a20d", features = ["bundled_proj"] }
```

However I'm now getting some nasty type errors from the basic example:

```rust
use proj::Proj;
//use geo::Point as GeoPoint;
use geo_types::Point as GeoTypesPoint;

fn main() {

    let from = "EPSG:2230";
    let to = "EPSG:26946";
    let nad_ft_to_m = Proj::new_known_crs(&from, &to, None).unwrap();
    let result = nad_ft_to_m
        .convert(GeoTypesPoint::new(4760096.421921f64, 3744293.729449f64))
        .unwrap();
    
    println!("{},{}", result.x(), result.y());
}
```

The error includes:
```
error[E0277]: the trait bound `geo_types::point::Point<_>: std::convert::From<geo_types::point::Point<f64>>` is not satisfied
  --> src/main.rs:15:10
   |
15 |         .convert(GeoTypesPoint::new(4760096.421921f64, 3744293.729449f64))
   |          ^^^^^^^ the trait `std::convert::From<geo_types::point::Point<f64>>` is not implemented for `geo_types::point::Point<_>`
   |
   = help: the following implementations were found:
             <geo_types::point::Point<T> as std::convert::From<(T, T)>>
             <geo_types::point::Point<T> as std::convert::From<[T; 2]>>
             <geo_types::point::Point<T> as std::convert::From<geo_types::coordinate::Coordinate<T>>>
   = note: required because of the requirements on the impl of `std::convert::Into<geo_types::point::Point<_>>` for `geo_types::point::Point<f64>`
```

My project also uses the `geo` crate (for the `HaversineDistance` trait) as I need to get distances between projected points, so I was wondering if the exported `geo_types` from the `geo` crate were interfering (hence the type aliasing), but it seems not to be the case.

**Comment by urschrei** [comment]
It's almost certainly because of mismatched geo-types versions, @simonhaines. Could you post the error you're seeing when trying to install the latest version?

**Comment by simonhaines** [comment]
Thanks @urschrei, I missed the new release while I was working on this issue and 0.20.2 works as expected.
