### ISSUE TITLE
proj-sys errors in build with gcc-13

### ISSUE THREAD

**Issue by prscoelho** [georust/proj#159]
Hey! It seems `9.1.0` fails to compile with gcc-13, due to errors like these:

```
  proj/proj-sys/PROJSRC/proj/proj-9.1.0/src/proj_json_streaming_writer.hpp:42:14: error: ‘int64_t’ in namespace ‘std’ does not name a type
     42 | typedef std::int64_t GIntBig;
```

And more, seems to be fixed by [this commit](https://github.com/OSGeo/PROJ/pull/3459), which made it to `9.1.1`. I just tested and it builds fine on `9.2.0` too.
